# Set up the Selenium container based on the Selenium official:
# https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3.yml
# And:
# https://medium.com/@retrorubies/chrome-as-a-service-for-rails-testing-b1a45e70fec1
services:
  web:
    image: lenchoreyes/jade:rails-app-${RUBY_VERSION:-3.4}-mysql-bookworm
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - NODE_ENV=development
      - BOOTSNAP_CACHE_DIR=/usr/local/bundle/_bootsnap
      - WEB_CONCURRENCY=1
      - HISTFILE=/app/.bash_history
      - DATABASE_HOST=mysql
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_APP_HOST=web
      - TEST_APP_PORT=3001
    ports:
      - ¨3000¨
      - ¨3001¨
      - "5990"
    command: /bin/bash
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11.2
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "exit | mariadb -h 127.0.0.1 -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s

  selenium:
    image: selenium/standalone-chrome:118.0
    logging:
      driver: none
    stdin_open: true
    tty: true
    environment:
      - LANG=en_CA.UTF-8
    ports:
      - "7900"

volumes:
  mariadb:
