name: build
run-name: ${{ github.actor }} is building Docker containers.
on:
  push:
    branches:
      - 'main'
    paths:
      - '**/Dockerfile'
      - .github/workflows/build.yml
  workflow_dispatch:
jobs:
  ruby-and-rails-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: ["3.0", "3.1", "3.2", "3.3", "3.4"]
        distro: [bullseye, bookworm]
        exclude:
          - distro: bookworm
            ruby_version: "3.0"
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Ruby App
        uses: docker/build-push-action@v5
        with:
          context: ruby-app
          build-args: |
            RUBY_VERSION=${{ matrix.ruby_version }}
            DISTRO=${{ matrix.distro }}
          tags: lenchoreyes/jade:ruby-app-${{ matrix.ruby_version }}-${{ matrix.distro }}
          push: true
      - name: Build and Push Rails App
        uses: docker/build-push-action@v5
        with:
          context: rails-app
          build-args: |
            RUBY_VERSION=${{ matrix.ruby_version }}
            DISTRO=${{ matrix.distro }}
            IMAGE=ruby-app
          tags: lenchoreyes/jade:rails-app-${{ matrix.ruby_version }}-${{ matrix.distro }}
          push: true
  rails-app-with-db:
    runs-on: ubuntu-latest
    needs: ruby-and-rails-app
    strategy:
      matrix:
        ruby_version: ["3.0", "3.1", "3.2", "3.3", "3.4"]
        distro: [bullseye, bookworm]
        database: [sqlite, postgres, mariadb, mysql]
        exclude:
          - distro: bookworm
            ruby_version: "3.0"
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Rails App with DB
        uses: docker/build-push-action@v5
        with:
          context: rails-app-${{ matrix.database }}
          build-args: |
            RUBY_VERSION=${{ matrix.ruby_version }}
            DISTRO=${{ matrix.distro }}
            IMAGE=rails-app
          tags: lenchoreyes/jade:rails-app-${{ matrix.ruby_version }}-${{ matrix.database }}-${{ matrix.distro }}
          push: true
