name: build
run-name: ${{ github.actor }} is building Docker containers.
on: workflow_dispatch
jobs:
  ruby-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: ["3.0", "3.1", "3.2", "3.3"]
        distro: [bullseye, bookworm]
        exclude:
          - distro: bookworm
            ruby_version: "3.0"
    steps:
      - uses: actions/checkout@v4
      - run: echo Build ${{ matrix.ruby_version }} ${{ matrix.distro }}
      - uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ruby-app
          build-args: |
            RUBY_VERSION=${{ matrix.ruby_version }}
            DISTRO=${{ matrix.distro }}
          tags: lenchoreyes/jade:ruby-app-${{ matrix.ruby_version }}-${{ matrix.distro }}
          outputs: .
      - name: Result
        run: ls -a
