name: build
run-name: ${{ github.actor }} is building Docker containers.
on: workflow_dispatch
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Build"
